version: '3'

services:
  database:
    image: mongo
    container_name: 'app-database'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE='docker-monitoring'
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/db
    restart: always
    networks:
      - monitoring-app
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - monitoring-app
  worker:
    build: ./docker/worker
    container_name: bull-worker
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/usr/project/worker
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    networks:
      - monitoring-app
      - anomaly-network
    links:
      - redis
    depends_on:
      - database

  app:
    build: ./docker/api
    container_name: app
    volumes:
      - /etc/localtime:/etc/localtime
      - .:/usr/project/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    links:
      - redis
      - database
    networks:
      - monitoring-app
      - anomaly-network

networks:
  monitoring-app:
    driver: bridge
  anomaly-network:
    external: true
